import {Injectable} from '@angular/core';

@Injectable({
	providedIn: 'root'
})
export class TimeSentencesService {
	public sentences: string[][] = [
		[
			"They play tennis every weekend.",
			"He plays tennis every weekend.",
			"They do not play tennis every weekend",
			"He does not play tennis every weekend",
			"Do they play tennis every weekend?",
			"Does he play tennis every weekend?",
		],
		[
			"I am playing tennis now", "They are playing tennis now", "He is playing tennis now",
			"I am not playing tennis now","They are not playing tennis now","He is not playing tennis now",
			"Am I playing tennis now?","Are they playing tennis now?","Is he playing tennis now?",
		],
		[
			"They have played tennis before","He has played tennis before",
			"They have not played tennis before","He has not played tennis before",
			"Have they played tennis before?","Has he played tennis before?",
		],
		[
			"They have been playing tennis since 1997.","He has been playing tennis since 1997.",
			"They have been playing tennis since 1997.","He has been playing tennis since 1997.",
			"They have not been playing tennis since 1997.","He has not been playing tennis since 1997.",
		],
		[
			"They played tennis yesterday.",
			"He played tennis yesterday.",
			"They did not play tennis yesterday.",
			"He did not play tennis yesterday.",
			"Did they play tennis yesterday?",
			"Did he play tennis yesterday?",
		],
		[
			"They were playing tennis at that moment",
			"He was playing tennis at that moment",
			"They were not playing tennis at that moment",
			"He was not playing tennis at that moment",
			"Were they playing tennis now?",
			"Was he playing tennis now?",
		],
		[
			"They had played tennis before the class started.","He had played tennis before the class started.",
			"They had not played tennis before the class started.","He had not played tennis before the class started.",
			"Had they played tennis before the class started?","Had he played tennis before the class started?",
		],
		[
			"He had been playing tennis for two hour.",
			"They had been playing tennis for two hour.",
			"We has not been playing tennis for two hours.",
			"She has not been playing tennis for two hours.",
			"Had he been playing tennis for two hours?",
			"Had you been playing tennis for two hours?",
		],
		[
			"He will play tennis tomorrow.",
			"We will play tennis tomorrow.",
			"He will not play tennis tomorrow.",
			"They will not play tennis tomorrow.",
			"Will he play tennis tomorrow?",
			"Will I play tennis tomorrow?",
		],
		[
			"They will be playing tennis tomorrow morning.",
			"He will be playing tennis tomorrow morning.",
			"They will not be playing tennis tomorrow morning.",
			"He will not be playing tennis tomorrow morning.",
			"Will they be playing tennis tomorrow morning?",
			"Will she be playing tennis tomorrow morning?",
		],
		[
			"He will have played tennis.",
			"We will have played tennis.",
			"They will not have played tennis.",
			"He will not have played tennis.",
			"Will he have played tennis?",
			"Will I have played tennis?",
		],
		[
			"He will have been playing tennis for 3 hours tomorrow.",
			"We will have been playing tennis for 3 hours tomorrow.",
			"He will not have been playing tennis for 3 hours tomorrow.",
			"They will not have been playing tennis for 3 hours tomorrow.",
			"Will he have been playing tennis tomorrow?",
			"Will I have been playing tennis tomorrow?",
		],
	]
	public structure: string[][] = [
		[
			"do/does+v",
			"dodoesv",
			"dodoes",
			"doesdov",
			"dov",
			"doesv",
			"vess",
			"vs",
			"ves",
			"dodoesnotv",
			"dodoesntv",
			"donotdoesnotv",
			"dontdoesnotv",
			"dontdoesntv",
			"donotv",
			"dontv",
			"doesnotv",
			"doesntv",
		],
		[
			"is/am/are+ving",
			"tobeving",
			"amisareving",
			"amareisving",
			"isamareving",
			"isareamving",
			"areisamving",
			"areamisving",
			"areving",
			"isving",
			"amving",
			"tobenotving",
			"amisarenotving",
			"amareisnotving",
			"isamarenotving",
			"isareamnotving",
			"areisamnotving",
			"areamisnotving",
			"arenotving",
			"isnotving",
			"amnotving",
			"tobentving",
			"ving",
			"amisarentving",
			"amareisntving",
			"isamarentving",
			"isareamntving",
			"areisamntving",
			"areamisntving",
			"arentving",
			"isntving",
			"amntving",
		],
		[
			"have/has+ved",
			"havehasvedv3",
			"hashavevedv3",
			"hasvedv3",
			"havevedv3",
			"havehasv3",
			"hashavev3",
			"hasv3",
			"havev3",
			"havehasved",
			"hashaveved",
			"hasved",
			"haveved",

			"havehasnotvedv3",
			"hashavenotvedv3",
			"havenothasnotvedv3",
			"hasnothavenotvedv3",
			"hasnotvedv3",
			"havenotvedv3",
			"havenothasnotv3",
			"hasnothavenotv3",
			"havehasnotv3",
			"hashavenotv3",
			"hasnotv3",
			"havenotv3",
			"havenothasnotved",
			"hasnothavenotved",
			"havehasnotved",
			"hashavenotved",
			"hasnotved",
			"havenotved",

			"havehasntvedv3",
			"hashaventvedv3",
			"haventhasntvedv3",
			"hasnthaventvedv3",
			"hasntvedv3",
			"haventvedv3",
			"haventhasntv3",
			"hasnthaventv3",
			"havehasntv3",
			"hashaventv3",
			"hasntv3",
			"haventv3",
			"haventhasntved",
			"hasnthaventved",
			"havehasntved",
			"hashaventved",
			"hasntved",
			"haventved",
		],
		[
			"have/has+been+ving",
			"havehasbeenving",
			"hashavebeenving",
			"hasbeenving",
			"havebeenving",
		],
		[
			"ved",
			"didv",
			"vedv2",
			"v2ved",
			"ved",
			"v2",
		],
		[
			"was/were+ving",
			"waswereving",
			"werewasving",
			"wereving",
			"wasving",
		],
		[
			"had+ved",
			"hadvedv3",
			"hadv3ved",
			"hadved",
			"hadv3",
		],
		[
			"had been+ving",
			"hadbeenving",
		],
		[
			"will+v",
			"willv",
			"vwill",
		],
		[
			"will be+ving",
			"willbeving",
		],
		[
			"will have+ved",
			"willhavevedv3",
			"willhavev3ved",
			"willhaveved",
			"willhavev3",
		],
		[
			"will have been+ving",
			"willhavebeenving",
		],
	]
	public words: string[][] = [
		[
			"обычно",
			"часто",
			"постоянно",
			"регулярно",
			"иногда",
			"каждый день",
			"каждую неделю",
			"каждую год",
			"always",
			"often",
			"generally",
			"regularly",
			"rarely",
			"seldom",
			"never",
			"every day",
			"sometimes",
			"usually",
		],
		[
			"сейчас",
			"в настоящий момент",
			"в настоящее время",
			"в данный момент",
			"сию минуту",
			"теперь",
			"сегодня",
			"прямо сейчас",
			"в эту минуту",
			"все ещё",
			"до сих пор",
			"now",
			"right now",
			"at the moment",
			"at present",
			"currently",
			"still",
			"these days",
		],
		[
			"уже",
			"давно",
			"ещё",
			"только что",
			"когда-либо",
			"до этого",
			"раньше",
			"все ещё",
			"только что",
			"никогда",
			"в последнее время",
			"недавно",
			"ever",
			"never",
			"just",
			"today",
			"already",
			"before",
			"lately",
			"for ages",
			"recently",
			"yet",
			"for",
			"since",
			"so far",
		],
		[
			"всегда",
			"иногда",
			"регулярно",
			"в следующем месяце",
			"на следующей неделе",
			"в следующем году",
			"в предыдущем месяце",
			"на предыдущей неделе",
			"в предыдущем году",
			"вчера",
			"завтра",
			"for",
			"since",
			"all",
			"recently",
			"whole",
		],
		[
			"вчера",
			"позавчера",
			"было",
			"произошло",
			"на прошлой неделе",
			"в прошлом месяце",
			"в прошлом году",
			"в прошлые выходные",
			"день назад",
			"неделю назад",
			"месяц назад",
			"год назад",
			"yesterday",
			"the day before",
			"that day",
			"the other day",
			"last week",
			"last month",
			"last year",
		],
		[
			"всю неделю",
			"в тот момент",
			"когда",
			"так как",
			"всю ночь",
			"весь год",
			"весь месяц",
			"весь день",
			"в то время, как",
			"at this time yesterday",
			"at that moment",
			"yesterday at",
			"from till",
			"the whole evening",
			"all day long",
			"all night long",
			"when",
			"while",
			"as",
		],
		[
			"раньше",
			"до того как",
			"никогда раньше",
			"едва",
			"как только",
			"к тому времени",
			"к вечеру",
			"к завтра",
			"перед тем как",
			"после того как",
			"раньше",
			"только что",
			"уже",
			"все ещё",
			"пока",
			"когда-либо",
			"когда либо",
			"пока что",
			"by",
			"before",
			"after",
			"when",
			"if",
			"just",
			"already",
			"yet",
			"since",
		],
		[
			"в течение",
			"к какому-то времени",
			"с тех пор как",
			"перед тем как",
			"когда",
			"в продолжение",
			"с того времени",
			"с того времени как",
			"перед",
			"перед тем как",
			"тогда",
			"затем",
			"псоле",
			"псоле того как",
			"потому что",
			"поскольку",
			"до тех пор",
			"до тех пор как",
			"так как",
			"пока",
			"for",
			"since",
			"before",
			"when",
			"while",
		],
		[
			"завтра",
			"скоро",
			"позже",
			"как только",
			"на следующей неделе",
			"на будущий год",
			"на будущий месяц",
			"в следующем месяце",
			"в следующем году",
			"однажды",
			"когда-нибудь",
			"на днях",
			"в будущем",
			"позже",
			"в скором врмени",
			"tomorrow",
			"the day before",
			"someday",
			"next week",
			"next month",
			"next year",
		],
		[
			"в тот момент",
			"тем временем",
			"с до",
			"сдо",
			"в течении этого времени",
			"в течении дня",
			"в течении недели",
			"в течении месяца",
			"в течении года",
			"в течении",
			"в это же время",
			"через неделю",
			"через день",
			"через месяц",
			"через год",
			"весь день",
			"весь год",
			"весь месяц",
			"весю неделю",
			"весю ночь",
			"next week",
			"next month",
			"next year",
			"this time tomorrow",
			"tonight",
			"from",
			"between",
			"while",
			"when",
			"still",
		],
		[
			"к тому времени",
			"к тому времени как",
			"перед тем как",
			"когда",
			"до того как",
			"до",
			"когда",
			"before",
			"till",
			"until",
			"by this time",
			"by",
			"by tomorrow",
			"by next week",
			"by next year",
			"by next month",
			"in a month",
			"in a year",
		],
		[
			"до того как",
			"на протяжении",
			"к концу",
			"когда",
			"for",
			"by",
			"by next week",
			"by next day",
			"by next month",
			"by next year",
			"when",
		],
	]

	constructor() {
	}
}
