import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class TimeSentencesService {
  public sentences: string[][]=[
    [
      "He plays football.",
      "They watch a movie.",
      "She goes to work.",
      "It snows here.",
      "We eat apples.",
      "Do you have a flat?",
      "Does he speak English?",
      "Do you play games?",
      "Does she listen to the radio?",
      "Do they play the guitar?",
      "I don't get up early.",
      "You don't have money.",
      "They don't go to work.",
      "We dont leave here.",
      "She does not ride a horse.",
    ],
    [
      "I am speaking on the phone.",
      "She is watching TV.",
      "They are working at shop.",
      "He is walking here.",
      "We are cleaning the house.",
      "He is not doing his homework.",
      "They are not washing the dishes.",
      "We are not dreaming.",
      "She is not cooking the dinner.",
      "They are not having lunch.",
      "Is it snowing outside?",
      "Is it raining today?",
      "Are you smiling?",
      "Are they singing?",
      "Is he playing tennis?",
    ],
    [
      "I have lived in London.",
      "You have seen a miracle.",
      "She has tried lunch.",
      "He has worked in a bank.",
      "We have bought a car.",
      "They have not passed an exam.",
      "She has not known him.",
      "They have not travelled to the moon.",
      "You have not learnt the lesson.",
      "We have not met yet.",
      "Have you bought a car?",
      "Have the students finished the task?",
      "Have you lost phone?",
      "Has she broken her leg?",
      "Have you been to New York?",
    ],
    [
      "I've been trying to call you all day!",
      "He's been waiting for you for six hours.",
      "I have been reading.",
      "We have been running.",
      "They have been working.",
      "She has not been eating breakfast.",
      "It has not been working.",
      "He has not been smoking.",
      "It has not been raining.",
      "She has not been talking.",
      "Has they been waiting us?",
      "Have we been driving the car?",
      "Has he been standing here?",
      "Have I been going there?",
      "Have they been listening?",
    ],
    [
      "I played the guitar.",
      "We studied here.",
      "He worked today.",
      "She moved to this house.",
      "They drove the car.",
      "We did not play hockey.",
      "I did not sleep.",
      "You did not tidy you room.",
      "They did not wash the dishes.",
      "She did not run.",
      "Did they film us?",
      "Did he return?",
      "Did we decided?",
      "Did she lived here?",
      "Did you talked?",
    ],
    [
      "I was eating lunch.",
      "They were working.",
      "He was sleeping.",
      "She was feeding the dog.",
      "He was singing.",
      "I was not reading the book.",
      "They were not having the dinner.",
      "We were not watching the sunset.",
      "She was not driving home.",
      "It was not raining all night.",
      "Was she playing the piano?",
      "Was he living in London?",
      "Was it snowing?",
      "Were they sleeping?",
      "Was she listening the story?",
    ],
    [
      "After she had finished her work, she went to dinner.",
      "Before I realized it, she had left the room.",
      "I called his office but he had already left.",
      "We saw that everybody had already gone.",
      "After he had become famous, I read his book.",
      "He asked me which animals I had not seen in Australia.",
      "It still had not snowed at the beginning of December.",
      "In the shopping mall I met a friend who I had not seen for ages.",
      "They thought that letters had not been sent yet.",
      "I had not learned Italian before I visited Milan.",
      "Had the plane arrived by that time?",
      "Had she done her homework before her sister came home?",
      "Had you eaten anything before you went to the theatre?",
      "Had he lived in New York before he moved to Los Angeles?",
      "Had they sold everything before they moved to Manchester?",
    ],
    [
      "I had been listening to music.",
      "We had been working in office.",
      "He had been driving the car.",
      "They had been playing football",
      "She had been waiting the bus.",
      "We had not been cooking the lunch.",
      "I had not been playing computer.",
      "It had not been raining.",
      "You had not been visiting parents.",
      "She had not been feeding the cat.",
      "Had you been washing the dishes?",
      "Had he been tiding the room?",
      "Had they been walking with the dog?",
      "Had we been swimming in the pool?",
      "Had you been eating the dinner?",
    ],
    [
      "I will visit you.",
      "He will come home.",
      "They will call a taxi.",
      "We will take a bus.",
      "She will watch the film",
      "I will not call you.",
      "He will not lose the game.",
      "They will not work.",
      "It will not happen again.",
      "She will not open the box.",
      "Will you open the door?",
      "Will they go shopping?",
      "Will you use the computer?",
      "Will it snow next week?",
      "Will he buy pizza?",
    ],
    [
      "I will be playing basketball.",
      "They will be having coffee.",
      "She will be going to the theatre.",
      "I will be meeting with my boss.",
      "We will be lying on the beach.",
      "They will not be watching TV.",
      "He will not be studying for his exam.",
      "I will not be cooking.",
      "She will not be working from home.",
      "You will not be playing computer games.",
      "Will they be coming with you?",
      "Will you be having dinner outside?",
      "Will he be waiting at the airport?",
      "Will we be going to the meeting tonight?",
      "Will I be working on project?",
    ],
    [
      "It will have finished when we arrive.",
      "She will have forgotten everything.",
      "He will have had his lunch.",
      "They will have arrived by Friday.",
      "We will have been in Canada.",
      "It will not have stopped raining.",
      "I will not have read this book.",
      "He will not have left for his holiday.",
      "They will not have moved to Australia.",
      "We will not have painted the house.",
      "Will you have finished the task by next Monday?",
      "Will he have gone to bed by 11 o’clock?",
      "Will they have built a school by this time next year?",
      "Will you have returned from the trip by then?",
      "Will Hanna have visited Rome in a week?",
    ],
    [
      "They will have been dating for 5 years by next year.",
      "I will have been learning English for one year.",
      "We will have been staying in Russia for three months.",
      "He will have been living in London.",
      "I will have been doing the chores.",
      "She will not have been working here.",
      "You will not have been playing tennis.",
      "It will not have been raining.",
      "They will not have been reading the book.",
      "We will not have been riding the horse.",
      "Will they have been cooking the dinner?",
      "Will she have been watching the film?",
      "Will you have been going to the cinema?",
      "Will he have been hitting the wall?",
      "Will they have been building a house?",
    ],
  ]
  public structure: string[][]=[
    [
      "dodoesv",
      "dodoes",
      "doesdov",
      "dov",
      "doesv",
      "vess",
      "vs",
      "ves",
      "dodoesnotv",
      "dodoesntv",
      "donotdoesnotv",
      "dontdoesnotv",
      "dontdoesntv",
      "donotv",
      "dontv",
      "doesnotv",
      "doesntv",
    ],
    [
      "tobeving",
      "amisareving",
      "amareisving",
      "isamareving",
      "isareamving",
      "areisamving",
      "areamisving",
      "areving",
      "isving",
      "amving",
      "tobenotving",
      "amisarenotving",
      "amareisnotving",
      "isamarenotving",
      "isareamnotving",
      "areisamnotving",
      "areamisnotving",
      "arenotving",
      "isnotving",
      "amnotving",
      "tobentving",
      "amisarentving",
      "amareisntving",
      "isamarentving",
      "isareamntving",
      "areisamntving",
      "areamisntving",
      "arentving",
      "isntving",
      "amntving",
    ],
    [
      "havehasvedv3",
      "hashavevedv3",
      "hasvedv3",
      "havevedv3",
      "havehasv3",
      "hashavev3",
      "hasv3",
      "havev3",
      "havehasved",
      "hashaveved",
      "hasved",
      "haveved",

      "havehasnotvedv3",
      "hashavenotvedv3",
      "havenothasnotvedv3",
      "hasnothavenotvedv3",
      "hasnotvedv3",
      "havenotvedv3",
      "havenothasnotv3",
      "hasnothavenotv3",
      "havehasnotv3",
      "hashavenotv3",
      "hasnotv3",
      "havenotv3",
      "havenothasnotved",
      "hasnothavenotved",
      "havehasnotved",
      "hashavenotved",
      "hasnotved",
      "havenotved",

      "havehasntvedv3",
      "hashaventvedv3",
      "haventhasntvedv3",
      "hasnthaventvedv3",
      "hasntvedv3",
      "haventvedv3",
      "haventhasntv3",
      "hasnthaventv3",
      "havehasntv3",
      "hashaventv3",
      "hasntv3",
      "haventv3",
      "haventhasntved",
      "hasnthaventved",
      "havehasntved",
      "hashaventved",
      "hasntved",
      "haventved",
    ],
    [
      "havehasbeenving",
      "hashavebeenving",
      "hasbeenving",
      "havebeenving",
    ],
    [
      "didvedv2",
      "didv2ved",
    ],
    [
      "waswereving",
      "werewasving",
      "wereving",
      "wasving",
    ],
    [
      "hadvedv3",
      "hadv3ved",
    ],
    [
      "hadbeenving",
    ],
    [
      "willv",
    ],
    [
      "willbeving",
    ],
    [
      "willhavevedv3",
      "willhavev3ved",
    ],
    [
      "willhavebeenving",
    ],
  ]
  public words: string[][]=[
    [
      "обычно",
      "часто",
      "регулярно",
      "повторяющееся действие",
      "регулярно повторяющееся действие",
      "часто повторяющееся действие",
      "иногда повторяющееся действие",
      "регулярное действие",
      "частое действие",
      "иногда",
      "каждый день",
      "каждую неделю",
      "каждую год",
    ],
    [
      "сейчас",
      "действие  происходящее в данный момент",
      "действие  происходящее сейчас",
      "действие  происходящее сегодня",
      "действие  происходящее все ещё",
      "действие  происходящее в эту минуту",
      "действие  происходящее прямо сейчас",
      "действие  происходящее сию минуту",
      "в настоящий момент",
      "в настоящее время",
      "в данный момент",
      "сию минуту",
      "теперь",
      "сегодня",
      "прямо сейчас",
      "в эту минуту",
      "все ещё",
      "до сих пор",
    ],
    [
      "уже",
      "когда-либо",
      "до этого",
      "раньше",
      "все ещё",
      "только что",
      "никогда",
      "в последнее время",
      "недавно",
      "действие, которое было недавно",
      "действие, которое происходило недавно",
      "действие которое было недавно",
      "действие которое происходило недавно недавно",
      "недавно бывшее действие",
    ],
    [
      "всегда",
      "иногда",
      "регулярно",
      "в следующем месяце",
      "на следующей неделе",
      "в следующем году",
      "в предыдущем месяце",
      "на предыдущей неделе",
      "в предыдущем году",
      "вчера",
      "завтра",
    ],
    [
      "вчера",
      "действие которое уже было",
      "действие которое было",
      "прозошедшее действие",
      "бывшее действие",
      "действие которое произошло",
      "позавчера",
      "было",
      "произошло",
      "на прошлой неделе",
      "в прошлом месяце",
      "в прошлом году",
      "в прошлые выходные",
      "день назад",
      "неделю назад",
      "месяц назад",
      "год назад",
      "в прошлом",
      "назад",
      "уже прошло",
      "прошлое",
    ],
    [
      "в данное время в прошлом",
      "в тот момент",
      "когда",
      "так как",
      "всю ночь",
      "всю неделю",
      "весь год",
      "весь месяц",
      "весь день",
      "в прошлое",
      "в прошлое время",
      "в то время, как",
    ],
    [
      "произошедшее до того как",
      "действие произошедшее до того как",
      "до того как",
      "никогда раньше",
      "раньше",
      "едва",
      "как только",
      "к тому времени",
      "к вечеру",
      "к завтра",
      "перед тем как",
      "после того как",
      "раньше",
      "только что",
      "уже",
      "все ещё",
      "пока",
      "когда-либо",
      "когда либо",
      "пока что",
    ],
    [
      "действие в течение периода в прошлом",
      "действие в течение периода времени в прошлом",
      "действие в течение какого-то периода времени в прошлом",
      "действие в течение какого-то периода в прошлом",
      "период в прошлом",
      "период времени в прошлом",
      "в течение",
      "к какому-то времени",
      "с тех пор как",
      "перед тем как",
      "когда",
      "в продолжение",
      "с того времени",
      "с того времени как",
      "перед",
      "перед тем как",
      "тогда",
      "затем",
      "псоле",
      "псоле того как",
      "потому что",
      "поскольку",
      "до тех пор",
      "до тех пор как",
      "так как",
      "пока",
    ],
    [
      "действие в будущем",
      "простое действие в будущем",
      "регулярное действие в будущем",
      "повторяющееся действие в будущем",
      "регулярное простое действие в будущем",
      "повторяющееся простое действие в будущем",
      "повтор в будущем",
      "скоро",
      "позже",
      "как только",
      "завтра",
      "на следующей неделе",
      "на будущий год",
      "на будущий месяц",
      "в следующем месяце",
      "в следующем году",
      "однажды",
      "когда-нибудь",
      "на днях",
      "в будущем",
      "позже",
      "в скором врмени",
    ],
    [
      "определенный момент в будущем",
      "определенный момент в будущем",
      "в тот момент",
      "тем временем",
      "с до",
      "сдо",
      "в течении этого времени",
      "в течении дня",
      "в течении недели",
      "в течении месяца",
      "в течении года",
      "в течении",
      "в это же время",
      "через неделю",
      "через день",
      "через месяц",
      "через год",
      "весь день",
      "весь год",
      "весь месяц",
      "весю неделю",
      "весю ночь",
    ],
    [
      "к каком-то времени",
      "к каком-то моменту",
      "к каком-то моменту времени",
      "к какому то времени",
      "к какому то моменту",
      "к какому то моменту времени",
      "к тому времени",
      "к тому времени как",
      "перед тем как",
      "когда",
      "до того как",
      "до",
      "когда",
    ],
    [
      "до того как",
      "на протяжении",
      "к концу",
      "в течении некоторого времени в будущем",
      "в течении некоторого времени",
      "до определенного события в будущем",
      "до определенного момента в будущем",
      "до определенного события",
      "до определенного момента",
      ],
  ]

  constructor() { }
}
